### ISSUE TITLE
Running a node?

### ISSUE THREAD

**Issue by moeadham** [kinecosystem/stellar-ops#8]
Hi,

Having a look at stellar-core.cfg shows the bootstrap nodes still appear to be IBM/stellar nodes. If we want to connect to the KIN stellar fork, where can we get the current bootstrap nodes from?

**Comment by oryband** [comment]
Hey @moeadham. Thanks for opening an issue!

That [`stellar-core.cfg`](https://github.com/kinecosystem/stellar-ops/blob/fb6077faccdb87a3af2bda40ca5fc6ca09e78b26/examples/stellar-core.cfg) file you're referring to is just an example configuration we put here for documentation sake. We aren't using it anywhere in production. I should've probably mentioned this more explicitly.

The Kik network, while an open network, is still in scaling testing. We'll probably commit related deployment files with addresses that you can use in the near future if you'd like to connect as a [watcher](https://www.stellar.org/developers/stellar-core/software/admin.html#level-of-participation-to-the-network) and observe the network. We'll also add more thorough documentation when it's ready.

Closing this issue for now. Please re-open if you have any questions.
